SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `user_like`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `user`(
  `username` VARCHAR (32) NOT NULL,
  `pwd` CHAR (32) NOT NULL,
  `name` VARCHAR (32) NOT NULL,
  `sex` VARCHAR (32) DEFAULT NULL,
  `age` VARCHAR (32) DEFAULT NULL,
  `phone` VARCHAR (16) NOT NULL,
  `email` VARCHAR (255) NOT NULL,
  `regdate` TIMESTAMP (2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
  PRIMARY KEY (`username`),
  UNIQUE KEY `phone`(`phone`),
  UNIQUE KEY `email`(`email`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_like`(
  `username` VARCHAR (32) NOT NULL,
  `field_like` CHAR (7) NOT NULL DEFAULT "1111000",
  `web_like` CHAR (6) NOT NULL DEFAULT "110000",
  KEY `username`(`username`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`username`) REFERENCES `user`(`username`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `news`;
CREATE TABLE `news`(
  `id` INT (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `news_date` VARCHAR(255) DEFAULT NULL,
  `content` TEXT NOT NULL,
  `source` CHAR(1) NOT NULL DEFAULT '0',
  `type` CHAR(1) NOT NULL DEFAULT '0',
  `image` VARCHAR(512) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;